# Задание 10.6
- Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

> Примечание: воспользуйтесь функцией [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) из библиотеки numpy, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

> Напоминание: в Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.

In [7]:
import numpy as np

def get_chess(a):
    arr = np.zeros((a, a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

print(get_chess(a = 5))

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


# Задание 10.7

- Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

- Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

In [52]:
import numpy as np

def shuffle_seed(array):
    seed = np.random.randint(2 ** 32 - 1, dtype=np.int64)
    np.random.seed(seed)
    result = np.random.permutation(array)
    return result, seed

 
array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([3, 2, 1, 5, 4]), 3370651527)

# Задание 10.8
Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

In [53]:
# 10.8

import numpy as np

def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
    return (min(dists), max(dists))

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

# Задание 10.9
Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [59]:
# 10.9

import numpy as np

def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3, 4])
print(any_normal(vec1, vec2, vec3))

True


# Задание 10.10
Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

In [64]:
# 10.10
import numpy as np

def get_loto(num):
    loto = np.random.randint(1, 101, size=(num, 5, 5))
    return loto
get_loto(3)

array([[[ 25,  13,  99,   2,  60],
        [ 66,  83,  39,  18,  34],
        [  4,  44,  15,  99,  81],
        [100,  65,  22,  32,  62],
        [ 37,   5,  59,  57,  36]],

       [[  8,  42,  65,   8,  53],
        [ 41,  81,  83,   4,   9],
        [ 72,  92,   1,  68,  32],
        [ 48,  25,  37,  69,  56],
        [ 32,  99,  28,  99,   9]],

       [[ 95,  16,  69,  32,  44],
        [ 94,  23,  70,  20,  13],
        [ 98,  18,  61,  47,  80],
        [ 63,  39,  97,  79,  25],
        [ 46,  62,  12,  12,  43]]])

# Задание 10.11

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 10.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.


In [72]:
# 10.11
import numpy as np

def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res

get_unique_loto(3)

array([[[  2,   7,  95,  83,  23],
        [ 18, 100,  26,  78,  80],
        [ 60,  47,  74,  10,  40],
        [ 72,  36,  71,  13,  22],
        [ 46,  82,  99,  41,   6]],

       [[ 98,  94,  25, 100,  89],
        [ 49,  72,  18,  69,   2],
        [ 81,  44,  79,  95,  63],
        [ 17,  70,  13,  47,  32],
        [ 48,  54,  31,  84,  67]],

       [[ 92,  19,  76,  38,  83],
        [ 86,   9,  57,   7,  99],
        [ 28,  53,  82,   1,  81],
        [ 97,  37,  98,  32,  47],
        [100,  63,  66,  43,  29]]])